import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { SanityLive } from "../studio-e_commerce-ai/lib/live.ts";
import { CartStoreProvider } from "@/lib/store/cart-store-provider";
import { ChatStoreProvider } from "@/lib/store/chat-store-provider";
import { Header } from "@/components/app/Header";
import { CartSheet } from "@/components/app/CartSheet";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", geistSans.variable, geistMono.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <CartStoreProvider>
            <ChatStoreProvider>
              <Header />
              <main>{children}</main>
              <CartSheet />
              <Toaster position="bottom-center" />
              <SanityLive />
            </ChatStoreProvider>
          </CartStoreProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
